import random
BOARD_ROWS = 25
BOARD_COLS = 50
CELL_SIZE = 20 # pixels per cell
WINDOW_WIDTH = BOARD_COLS * CELL_SIZE
WINDOW_HEIGHT = BOARD_ROWS * CELL_SIZE

BACKGROUND_COLOR = (00,64,00)

SOLDIER_ROWS = 4
SOLDIER_COLS = 2
SOLDIER_BODY_ROWS = 3 # the upper part
SOLDIER_FEET_ROWS = 1 # the lower part
SOLDIER_WIDTH = SOLDIER_COLS*CELL_SIZE
SOLDIER_HEIGHT = SOLDIER_ROWS*CELL_SIZE
SOLDIER_PNG = "soldier.png"
NIGHT_SOLD_PNG = "soldier_nigth.png"
SOLDIER_LEGS_HEIGHT = SOLDIER_FEET_ROWS*CELL_SIZE
SOLDIER_BODY_HEIGHT = SOLDIER_BODY_ROWS*CELL_SIZE

FLAG_ROWS = 3
FLAG_COLS = 4
flag_row = BOARD_ROWS - FLAG_ROWS
flag_col = BOARD_COLS - FLAG_COLS
FLAG_PNG = "flag.png"

MINES_COUNT = 20
MINE_ROWS = 1
MINE_COLS = 3
MINE_PNG = "mine.png"

BUSH_PNG = "grass.png"
bush_lst = []
for bush in range(20):
    r = random.randint(0, BOARD_ROWS - 1)
    c = random.randint(0, BOARD_COLS - 1)
    bush_lst.append([r,c])

FONT_NAME = "Arial"
WELCOME_COLOR = (0,0,0)
WELCOME_MESSAGE = (f"Welcome to The Flag game.\n"
                   f"Have Fun!")
WELCOME_FONT_SIZE = int(0.02 * WINDOW_WIDTH)
WELCOME_LOCATION = \
(10,WELCOME_FONT_SIZE)

LOSE_MESSAGE = "You Lost!"
LOSE_FONT_SIZE = int(0.15 * WINDOW_WIDTH)
LOSE_COLOR = (0,0,0)
LOSE_LOCATION = \
    (0.2 * WINDOW_WIDTH, WINDOW_HEIGHT / 2 - (LOSE_FONT_SIZE / 2))

WIN_MESSAGE = "You Won!"
WIN_FONT_SIZE = LOSE_FONT_SIZE
WIN_COLOR = (0,0,0)
WIN_LOCATION = \
    (0.2 * WINDOW_WIDTH, WINDOW_HEIGHT / 2 - (WIN_FONT_SIZE / 2))

EMPTY_TILE = 0
MINE_TILE = 1
FLAG_TILE = 2
PLAYER_TILE = 3

RUNNING_STATE = 0
LOSE_STATE = 1
WIN_STATE = 2
SHOW_MINES_STATE = 3